const STATE_STYLE: Record<string, string> = {
  CREATED: "badge-neutral",
  INDEXING: "badge-accent",
  INDEXED: "badge-accent",
  PLANNING: "badge-accent",
  PLAN_READY: "badge-accent",
  AWAITING_PLAN_APPROVAL: "badge-warn",
  PLAN_REJECTED: "badge-danger",
  CHANGES_GENERATING: "badge-accent",
  CHANGES_READY: "badge-accent",
  AWAITING_CHANGE_APPROVAL: "badge-warn",
  CHANGES_REJECTED: "badge-danger",
  TESTS_GENERATING: "badge-accent",
  VALIDATING: "badge-accent",
  VALIDATION_FAILED: "badge-danger",
  REPAIRING: "badge-warn",
  VALIDATION_PASSED: "badge-success",
  AWAITING_COMMIT_APPROVAL: "badge-warn",
  COMMITTED: "badge-success",
  CI_RUNNING: "badge-accent",
  COMPLETED: "badge-success",
  FAILED: "badge-danger",
  passed: "badge-success",
  failed: "badge-danger",
  error: "badge-danger",
  skipped: "badge-neutral",
  pending: "badge-neutral",
  // Guardrail Control Plane statuses/actions (uppercase, as returned by
  // GET /api/guardrails*).
  PASSED: "badge-success",
  WARNING: "badge-warn",
  BLOCKED: "badge-danger",
  NOT_APPLICABLE: "badge-neutral",
  NOT_IMPLEMENTED: "badge-neutral",
  ALLOW: "badge-success",
  WARN: "badge-warn",
  REQUIRE_APPROVAL: "badge-accent",
  BLOCK: "badge-danger",
  ABORT: "badge-danger",
  LOW: "badge-neutral",
  MEDIUM: "badge-accent",
  HIGH: "badge-warn",
  CRITICAL: "badge-danger",
  // Final-report evidence classification (Part 14).
  FACT: "badge-success",
  INFERRED: "badge-accent",
  ASSUMPTION: "badge-warn",
  UNKNOWN: "badge-neutral",
  UNVERIFIED: "badge-danger",
  READY: "badge-success",
  READY_WITH_WARNINGS: "badge-warn",
  NOT_READY: "badge-danger",
};

export function StatusBadge({ state }: { state: string }) {
  const cls = STATE_STYLE[state] || "badge-neutral";
  return <span className={`badge ${cls}`}>{state.replace(/_/g, " ")}</span>;
}
